---
servers:
  'Main Server':
    host: 'server.fith.co'
    port: 27015
  'Dodgeball/Fun':
    host: 'server.fith.co'
    port: 27060
  'JUMBO':
    host: 'server.fith.co'
    port: 27069

display: 'ili9341'
summary: true
details: false
show_fps: false
font_size: 16
debug: false
