---
servers:
  'Main Server':
    host: '216.52.148.223'
    port: 27015
  'Dodgeball/Fun':
    host: '216.52.148.223'
    port: 27060
  'JUMBO':
    host: '216.52.148.223'
    port: 27069

display: 'ili9341'
summary: true
details: false
